apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web-app
    spec:
      containers:
        - image: quberegistry1.azurecr.io/qube-sample-webapp_web_app:v1
          name: web-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
