apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: qube-app
  name: qube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qube-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: qube-app
    spec:
      containers:
        - env:
            - name: QUBE_JAVA_OPTS
              value: -Dqube.es.host=qube-db
            - name: SERVER_PORT
              value: ''
          image: quberegistry1.azurecr.io/qube:1.1
          name: qube-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
